version: "2"

services:

  db:
    image: mysql:latest
    container_name: mysql123
    ports:
      - "51156:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  python-task:
    image: python:3-onbuild
    container_name: python123
    build: ./scripts/
    links:
      - db
    ports:
      - "51459:5000"
