version: "2"

services:

  sql-service:
    image: mysql:latest
    container_name: mysql-2
    ports:
      - "51156:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  python-service:
    image: python:3-onbuild
    container_name: python-2
    build: ./scripts/
    links:
      - sql-service
    ports:
      - "51459:5000"
